#Copyright (c) 2020 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


# This Playbook collects the ip adresses of the arp cache based on a given vlan_id



- name: Play 1 Get Network Information
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"

  tasks:

    - name: Get arp Cache
      nxos_command: 
        commands: "show ip arp vlan {{ vlan_id }} vrf all"
      register: qResult

##### set some facts and calculated vrrp lcl addresses out of gateway variable
    - set_fact:
        x: "{{ qResult.stdout | join }}"
        vrrp1: "{{ gateway | ipmath(1) }}"
        vrrp2: "{{ gateway | ipmath(2) }}"

#### Generate List from output containing only IP Addresses
    - set_fact:
        matches: "{{ x | regex_findall('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}', '\\1') }}"

#### Remove VRRP IPs from Precheck List
    - set_fact:    
        cleanList: "{{ matches | reject('search', vrrp2 ) | list }}"

    - set_stats:
        data:
          preCheck: "{{ cleanList | sort }}"
        per_host: no