#Copyright (c) 2020 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


#This Playbook moves a given list of vms from one DC to another
# "{{ vm_name }}"
# "{{ dest_host_name }}"
# "{{ dest_dstore_name }}"
# source_dc 
# "{{ dest_dc }}"
# "{{ dest_network_name }}"

- name: uc03_move_aci_vms
  hosts: all
  connection: local
  gather_facts: no
########

  tasks:

#### set AP Name out of vlan_id
      - set_fact: 
              ap_name: "Vlan{{ vlan_id }}"

### change the network
      - name: Change the network
        vmware_guest:
          hostname: "{{ inventory_hostname }}"
          username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
          password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
          validate_certs: False
          name: "{{ item }}"
          datacenter: "{{ source_dc }}"
          networks: 
           - name: "VM Network"
        with_items: "{{ vm_name }}"


### move the vms

      - name: Perform storage vMotion and host vMotion of virtual machine
        vmware_vmotion:
          hostname: "{{ inventory_hostname }}"
          username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
          password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
          validate_certs: False
          vm_name: "{{ item }}"
          destination_host: "{{ dest_host_name }}"
          destination_datastore: "{{ dest_dstore_name }}"
        delegate_to: localhost
        with_items: "{{ vm_name }}"

### change the network
      - name: Change the network
        vmware_guest:
          hostname: "{{ inventory_hostname }}"
          username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
          password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
          validate_certs: False
          name: "{{ item }}"
          datacenter: "{{ dest_dc }}"
          networks: 
           - name: "{{ tenant_name }}|{{ ap_name }}|{{ ap_name }}_EPG"
        with_items: "{{ vm_name }}"
        retries: 30 
        delay: 5
