### Copyright (c) 2020 Cisco and/or its affiliates.
### 
### This software is licensed to you under the terms of the Cisco Sample
### Code License, Version 1.1 (the "License"). You may obtain a copy of the
### License at
### 
###                https://developer.cisco.com/docs/licenses
### 
### All use of the material herein must be in accordance with the terms of
### the License. All rights not expressly granted by the License are
### reserved. Unless required by applicable law or agreed to separately in
### writing, software distributed under the License is distributed on an "AS
### IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
### or implied.


### This Playbook shuts down a given interface
### vars:
### istatus: interface status
### vlan_id: vlan v



- name: Play 1 add line to a file
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
#######

  tasks:

    - set_fact: 
        interface_name: "Vlan{{ vlan_id }}"

##### Shutdown interface
    - name: Change Interface {{ interface_name }}
      nxos_interfaces:
        config:
          - name: "{{ interface_name }}"
            enabled: "{{ istatus }}"
        state: merged


    - set_stats:
        data:
          webextext: ".:|:.:|:. I shut off Interface {{ interface_name }} on {{ inventory_hostname }} .:|:.:|:. \n"
        per_host: no
      when: istatus != 'True'