#Copyright (c) 2020 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


### This Playbooks "migrates" a gateway
### more specific: it modifies an existing l2 BD
### vars:
### vlan_id: vlan id
### tenant_name: tenant name
###



- name: Play 1 Migrate 
  hosts: all
  gather_facts: no

  tasks:


### Login Stuff
   - set_fact:
      aci_login: &aci_login
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        use_ssl: yes
        validate_certs: no


### AP Name out of vlan_id
   - set_fact: 
        ap_name: "Vlan{{ vlan_id }}"


##### "Migrate Gateway"
   - name: Migrate GW
     aci_bd_subnet:
       <<: *aci_login
       tenant: "{{ tenant_name }}"
       bd: "{{ ap_name }}_BD"
       gateway: "{{ gateway }}"
       mask: "{{ gw_cidr }}"
       scope: public
       state: present
     delegate_to: localhost   


#### Modify existing Bridge Domain
   - name: Modify Bridge Domain 
     aci_bd:
       <<: *aci_login
       tenant: "{{ tenant_name }}"
       bd: "{{ ap_name }}_BD"
       vrf: "{{ tenant_name }}_VRF"
       l2_unknown_unicast: proxy
       arp_flooding: false
       enable_routing: true
       state: present
     delegate_to: localhost


### Set WebEx Text
   - set_stats:
       data:
         webextext: ".:|:.:|:. Gateway Migration of {{ gateway }} for VLAN{{ vlan_id }} is done. .:|:.:|:."
       per_host: no
       