Copyright (c) 2020 Cisco and/or its affiliates.

This software is licensed to you under the terms of the Cisco Sample
Code License, Version 1.1 (the "License"). You may obtain a copy of the
License at

               https://developer.cisco.com/docs/licenses

All use of the material herein must be in accordance with the terms of
the License. All rights not expressly granted by the License are
reserved. Unless required by applicable law or agreed to separately in
writing, software distributed under the License is distributed on an "AS
IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied.

### vars needed
### dcnmhost - ip adress or dns name; IP/Name of DCNM Host
### dcnmapitoken - apitoken; Authenticate against dcnm api
### multisite_fabric_name - string; Name of Multisite Fabric
### deployment - boolean; true=attach,false=detach
### vlan_id - integer; 1 - 4096
### network_name - string; Name of the network
### nonvpc_devices - array; { sn: "Serial Number", fn: "Site Name", in: "Interface Name" }
### vpc_devices - array; { sn_vpc1: "Serial Number", fn_vpc1: "Site Name", in_vpc1: "Interface Name", sn_vpc2: "Serial Number", fn_vpc2: "Site Name", in_vpc2: "Interface Name" }
###
### vars provided
### 

- name: Attach or detach networks to fabric
  hosts: all
  connection: local
  gather_facts: no


  tasks:

    - name: Modify network on nonVPC devices
      uri:
          url: https://{{ dcnmhost }}/rest/top-down/fabrics/{{ multisite_fabric_name }}/networks/attachments
          headers:
            Dcnm-token: "{{ dcnmapitoken }}"
            Content-Type: "application/json"
          method: POST
          body_format: json
          body:
            [
              {
                "networkName": "{{ network_name }}",
                "lanAttachList": [
                  {
                    "fabric": "{{ item.fn }}",
                    "networkName": "{{ network_name }}",
                    "serialNumber": "{{ item.sn }}",
                    "vlan": "{{ vlan_id }}",
                    "dot1QVlan": 1,
                    "untagged": false,
                    "freeformConfig": "",
                    "deployment": "{{ deployment }}",
                    "extensionValues": "{\"MULTISITE_CONN\":\"{\\\"MULTISITE_CONN\\\":[]}\"}",
                    "switchPorts": "{{ item.in }}",
                    "detachSwitchPorts": "",
                    "instanceValues": ""
                  }
                ]
              }
            ]
          status_code: 200
          return_content: yes
          validate_certs: no
      with_items: "{{ nonvpc_devices }}"

    - name: 2. Modify network on VPC devices
      uri:
          url: https://{{ dcnmhost }}/rest/top-down/fabrics/{{ multisite_fabric_name }}/networks/attachments
          headers:
            Dcnm-token: "{{ dcnmapitoken }}"
            Content-Type: "application/json"
          method: POST
          body_format: json
          body:
            [
              {
                "networkName": "{{ network_name }}",
                "lanAttachList": [
                  {
                    "fabric": "{{ item.fn_vpc1 }}",
                    "networkName": "{{ network_name }}",
                    "serialNumber": "{{ item.sn_vpc1 }}",
                    "vlan": "{{ vlan_id }}",
                    "dot1QVlan": 1,
                    "untagged": false,
                    "freeformConfig": "",
                    "deployment": "{{ deployment }}",
                    "extensionValues": "{\"MULTISITE_CONN\":\"{\\\"MULTISITE_CONN\\\":[]}\"}",
                    "switchPorts": "{{ item.in_vpc1 }}",
                    "detachSwitchPorts": "",
                    "instanceValues": ""
                  },
                  {
                    "fabric": "{{ item.fn_vpc2 }}",
                    "networkName": "{{ network_name }}",
                    "serialNumber": "{{ item.sn_vpc2 }}",
                    "vlan": "{{ vlan_id }}",
                    "dot1QVlan": 1,
                    "untagged": false,
                    "freeformConfig": "",
                    "deployment": "{{ deployment }}",
                    "extensionValues": "{\"MULTISITE_CONN\":\"{\\\"MULTISITE_CONN\\\":[]}\"}",
                    "switchPorts": "{{ item.in_vpc2 }}",
                    "detachSwitchPorts": "",
                    "instanceValues": ""
                  }
                ]
              }
            ]
          status_code: 200
          return_content: yes
          validate_certs: no
      with_items: "{{ vpc_devices }}"